// Regenerate src/levels-data.js from the hand-authored levels in docs/levels/.
//
//   node scripts/gen-levels.mjs
//
// Each docs/levels/*.json is a `mycelium-level` document exported by the level
// editor (docs/level-editor.html). Levels with a `campaignLevel` number replace
// the procedural map for that campaign level; the rest are just parked here (the
// editor can still load them). The game can't `import` JSON in a plain <script
// type=module> bundle, so the JSON is baked into a JS module — same pattern as
// cards.json -> src/cards-data.js. NEVER hand-edit src/levels-data.js.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dir = join(root, 'docs', 'levels');
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
const levels = [];
for (const f of files) {
  const raw = readFileSync(join(dir, f), 'utf8');
  let obj;
  try { obj = JSON.parse(raw); } catch (e) { throw new Error(`docs/levels/${f}: invalid JSON — ${e.message}`); }
  if (obj.format !== 'mycelium-level') throw new Error(`docs/levels/${f}: not a mycelium-level document`);
  if (!Array.isArray(obj.objects)) throw new Error(`docs/levels/${f}: missing objects[]`);
  obj.file = f;
  levels.push(obj);
}

// Two authored levels claiming the same campaign slot is always a mistake — the
// second would silently win. Fail the generate instead.
const claimed = new Map();
for (const l of levels) {
  if (l.campaignLevel == null) continue;
  const n = l.campaignLevel | 0;
  if (claimed.has(n)) throw new Error(`campaignLevel ${n} claimed by both ${claimed.get(n)} and ${l.file}`);
  claimed.set(n, l.file);
}

const body = levels.map((l) => JSON.stringify(l)).join(',\n  ');
const out = `// GENERATED by scripts/gen-levels.mjs from docs/levels/*.json — DO NOT EDIT.
//
// Hand-authored levels (docs/level-editor.html). A level whose \`campaignLevel\` is
// set REPLACES the procedural map for that campaign level; others are inert here.
// To add one: export the JSON from the editor into docs/levels/, run
// \`node scripts/gen-levels.mjs\`, then \`node build.mjs\`.

export const LEVELS = [
  ${body}
];

// The authored level for campaign level \`n\`, or null to generate procedurally.
export function levelForNumber(n) {
  for (const l of LEVELS) if ((l.campaignLevel | 0) === (n | 0) && l.campaignLevel != null) return l;
  return null;
}
`;

writeFileSync(join(root, 'src', 'levels-data.js'), out);
console.log(`Wrote src/levels-data.js — ${levels.length} level(s)` +
  (claimed.size ? `, campaign slots: ${[...claimed.keys()].sort((a, b) => a - b).join(', ')}` : ', none wired to the campaign'));
