// =============================================================================
// Card data — GENERATED from docs/cards.json (do not edit by hand).
// Regenerate: node scripts/gen-carddata.mjs
// Engine-relevant fields only. Effects are dispatched by name in engine/cards.js.
// =============================================================================
export const CARD_DATA = [
 {
  "name": "Hyphal Extension",
  "type": "basic",
  "category": "growth",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 1 step: toward all food sources in range.",
  "family": "basics",
  "tutorial": true,
  "startCopies": 5
 },
 {
  "name": "Leaf Litter Cache",
  "type": "basic",
  "category": "substrate",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a SMALL nutrient patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Acorn Cache",
  "type": "basic",
  "category": "substrate",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a SMALL nut cache at the edge of sensing range.",
  "family": "basics",
  "tutorial": true,
  "startCopies": 5
 },
 {
  "name": "Apical Drive",
  "type": "basic",
  "category": "growth",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 2 steps: choose a direction.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Foraging Fan",
  "type": "basic",
  "category": "growth",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 1 step: every direction.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Tropic Lunge",
  "type": "basic",
  "category": "growth",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 5 steps toward the nearest food source, even if out of range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Humus Bed",
  "type": "basic",
  "category": "substrate",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a MEDIUM patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Mycorrhizal Mat",
  "type": "basic",
  "category": "substrate",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a LARGE patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Saprotrophic Digest",
  "type": "basic",
  "category": "economy",
  "displayCategory": "basic",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Drain 1 nutrient from every occupied food source, doubling the energy received.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Appressorial Punch",
  "type": "basic",
  "category": "utility",
  "displayCategory": "event",
  "buyCostEnergy": 1,
  "costW": 1,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow through one in-range rock.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Sclerotial Crust",
  "type": "basic",
  "category": "defense",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 2,
  "timing": "mid",
  "repay": 0,
  "threat": "all",
  "produces": "",
  "effect": "Tap a point: strands within radius 60 harden — permanently immune to infection and eating.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Hyphal Imbibition",
  "type": "basic",
  "category": "water-harvest",
  "displayCategory": "event",
  "buyCostEnergy": 3,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+9 Water lakeside / +3 Water from soil",
  "effect": "If your network touches a lake edge, harvest +9 Water. Otherwise gain +3 Water from soil.",
  "family": "water",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Phosphate Tap",
  "type": "basic",
  "category": "phosphorus-mining",
  "displayCategory": "event",
  "buyCostEnergy": 3,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+3 Phosphorus on harvest",
  "effect": "If your network contacts any mineral, crystal, or boulder, harvest +5 Phosphorus.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Condense",
  "type": "basic",
  "category": "water-harvest",
  "displayCategory": "event",
  "buyCostEnergy": 2,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+3 Water",
  "effect": "Gain 5 Water.",
  "family": "water",
  "tutorial": false,
  "startCopies": 5
 },
 {
  "name": "Rhizomorph Trunkline",
  "type": "engine",
  "category": "energy income",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "mid",
  "repay": 3,
  "threat": "none",
  "produces": "+2 energy/round",
  "effect": "Gain +2 energy every round.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Osmotic Cashout",
  "type": "event",
  "category": "energy burst",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 4,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Gain +22 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Aquaporin Channels",
  "type": "engine",
  "category": "water-engine",
  "displayCategory": "engine",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 4,
  "threat": "none",
  "produces": "+1 Water / 2 rounds",
  "effect": "Gain +1 Water every 2 rounds.",
  "family": "water",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Phosphatase Cushion",
  "type": "engine",
  "category": "phosphorus-producer",
  "displayCategory": "engine",
  "buyCostEnergy": 12,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 3,
  "threat": "none",
  "produces": "+2 Phosphorus / 8 rounds",
  "effect": "Gain +2 Phosphorus every 8 rounds.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Mineralizing Saprobe",
  "type": "engine",
  "category": "decay / unconditional P production",
  "displayCategory": "engine",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 4,
  "threat": "none",
  "produces": "+1 Phosphorus / 5 rounds",
  "effect": "Gain +1 Phosphorus every 5 rounds.",
  "family": "phosphorus",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Tap-Root Rhizomorph",
  "type": "action",
  "category": "routing",
  "displayCategory": "engine",
  "buyCostEnergy": 12,
  "costW": 0,
  "costP": 2,
  "timing": "mid",
  "repay": 4,
  "threat": "none",
  "produces": "grow through 1 in-range rock per use (every 10 rounds, 2 P)",
  "effect": "Once per 10 rounds: Pay 2 P to grow through an in-range rock.",
  "family": "growth",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Constricting Ring",
  "type": "action",
  "category": "anti-worm",
  "displayCategory": "engine",
  "buyCostEnergy": 12,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "worm",
  "produces": "",
  "effect": "Once per 6 rounds: tap a point where no nematode is within range; the first to enter is digested for +2 P.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Rehydration Pulse",
  "type": "event",
  "category": "water-repair",
  "displayCategory": "event",
  "buyCostEnergy": 7,
  "costW": 3,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "all",
  "produces": "",
  "effect": "Pay 3 Water: tap a point; heal all mold damage within radius 60.",
  "family": "water",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Nutrient Transmutation",
  "type": "action",
  "category": "resource converter",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per round: spend 2 of one resource (W/P) to gain 1 of the other.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Rhizomorph Lance",
  "type": "event",
  "category": "mobility",
  "displayCategory": "basic",
  "buyCostEnergy": 1,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow up to 6 steps: choose a direction.",
  "family": "events",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Fruiting Vigil",
  "type": "event",
  "category": "finisher",
  "displayCategory": "event",
  "buyCostEnergy": 2,
  "costW": 1,
  "costP": 2,
  "timing": "late",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow up to 8 steps: choose a direction.",
  "family": "events",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Leading Cord",
  "type": "action",
  "category": "growth",
  "displayCategory": "engine",
  "buyCostEnergy": 6,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to grow 2 steps in a chosen direction.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Forager Bloom",
  "type": "action",
  "category": "growth",
  "displayCategory": "engine",
  "buyCostEnergy": 5,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to fan out, growing 1 step in every direction.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Questing Front",
  "type": "action",
  "category": "growth",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 2,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 2 W to grow 5 steps toward the nearest food, even out of range.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Humus Cache",
  "type": "extender",
  "category": "draw-engine",
  "displayCategory": "extender",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Humus Bed basics",
  "effect": "Shuffle 5 copies of Humus Bed into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Symbiont Weave",
  "type": "extender",
  "category": "draw-engine",
  "displayCategory": "extender",
  "buyCostEnergy": 9,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Mycorrhizal Mat basics",
  "effect": "Shuffle 5 copies of Mycorrhizal Mat into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Enzyme Priming",
  "type": "extender",
  "category": "draw-engine",
  "displayCategory": "extender",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Saprotrophic Digest basics",
  "effect": "Shuffle 5 copies of Saprotrophic Digest into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Crust Reserve",
  "type": "action",
  "category": "anti-mould",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 2 P to harden a patch, clearing mold and making it immune to future infection.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Capillary Runners",
  "type": "engine",
  "category": "water-engine",
  "displayCategory": "engine",
  "buyCostEnergy": 9,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Gain +3 Water every 6 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Prospecting Cords",
  "type": "engine",
  "category": "phosphorus-producer",
  "displayCategory": "engine",
  "buyCostEnergy": 6,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+1 Phosphorus / 8 rounds",
  "effect": "Gain +1 Phosphorus every 8 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Dew Traps",
  "type": "engine",
  "category": "water-engine",
  "displayCategory": "engine",
  "buyCostEnergy": 11,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+2 Water / 3 rounds",
  "effect": "Gain +2 Water every 3 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Colonizing Front",
  "type": "action",
  "category": "growth",
  "displayCategory": "engine",
  "buyCostEnergy": 5,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to grow 1 step toward all food in range.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Leaf Fall",
  "type": "extender",
  "category": "draw-engine",
  "displayCategory": "extender",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Leaf Litter Cache basics",
  "effect": "Shuffle 5 copies of Leaf Litter Cache into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Acorn Fall",
  "type": "action",
  "category": "substrate",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to bury a small nut cache at the sensing edge.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Sclerotial Seal",
  "type": "action",
  "category": "anti-ant",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "ant",
  "produces": "",
  "effect": "Once per 10 rounds: Pay 1 P to permanently seal any food pile from ant access.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Suberin Wall",
  "type": "action",
  "category": "anti-mould",
  "displayCategory": "engine",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 3,
  "timing": "any",
  "repay": 0,
  "threat": "mould",
  "produces": "",
  "effect": "Once per 8 rounds: Pay 3 P to tap a point to clear all infection and permanently protect from reinfection.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Quickened Reflex",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 10,
  "costW": 2,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed \"use\" card: it becomes ready 1 round faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Impulse Relay",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 18,
  "costW": 4,
  "costP": 4,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed \"use\" card: it becomes ready 2 rounds faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Hair-Trigger Hyphae",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 28,
  "costW": 6,
  "costP": 6,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed \"use\" card: it becomes ready 3 rounds faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Brisk Metabolism",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 10,
  "costW": 2,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed resource generation card: it becomes ready 1 round faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Enzyme Overclock",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 18,
  "costW": 4,
  "costP": 4,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed resource generation card: it becomes ready 2 rounds faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Metabolic Surge",
  "type": "event",
  "category": "tempo",
  "displayCategory": "engine",
  "buyCostEnergy": 28,
  "costW": 6,
  "costP": 6,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Permanently speed up one installed resource generation card: it becomes ready 3 rounds faster. Max 1 per card.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Turgor Spark",
  "type": "event",
  "category": "energy burst",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+13 energy",
  "effect": "Gain +13 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Vacuolar Burst",
  "type": "event",
  "category": "energy burst",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 5,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+33 energy",
  "effect": "Gain +33 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Glycogen Crush",
  "type": "event",
  "category": "energy burst",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 8,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+54 energy",
  "effect": "Gain +54 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Cytoplasmic Cascade",
  "type": "event",
  "category": "energy burst",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 12,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+82 energy",
  "effect": "Gain +82 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Cord Capillary",
  "type": "engine",
  "category": "energy income",
  "displayCategory": "engine",
  "buyCostEnergy": 6,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+1 energy/round",
  "effect": "Gain +1 energy every round.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Rhizomorph Dynamo",
  "type": "engine",
  "category": "energy income",
  "displayCategory": "engine",
  "buyCostEnergy": 15,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+3 energy/round",
  "effect": "Gain +3 energy every round.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Amputate",
  "type": "basic",
  "category": "defense",
  "displayCategory": "event",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Tap a point: remove all mycelium within a radius — cut off infection.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 4
 },
 {
  "name": "Severing Cords",
  "type": "action",
  "category": "defense",
  "displayCategory": "engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 8 rounds: Pay 2P to tap to remove all mycelium within a radius.",
  "family": "defense",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Sclerotial Rind",
  "type": "action",
  "category": "defense",
  "displayCategory": "engine",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: Pay 1 P to harden strands in a radius — permanently immune to infection and eating.",
  "family": "defense",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Constricting Snap",
  "type": "event",
  "category": "anti-worm",
  "displayCategory": "event",
  "buyCostEnergy": 5,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "worm",
  "produces": "",
  "effect": "Tap a point: the nearest nematode within range is throttled and digested for +3 P.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Toxocyst Burst",
  "type": "event",
  "category": "anti-worm",
  "displayCategory": "event",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "worm",
  "produces": "",
  "effect": "Tap a point: every nematode within a radius is paralysed and digested (+1 P each).",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Toxocyst Array",
  "type": "action",
  "category": "anti-worm",
  "displayCategory": "engine",
  "buyCostEnergy": 13,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "worm",
  "produces": "",
  "effect": "Once per 8 rounds: tap a point — every nematode within a radius is digested.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Cordyceps Bloom",
  "type": "event",
  "category": "anti-ant",
  "displayCategory": "event",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "ant",
  "produces": "",
  "effect": "Destroy the nearest ant nest within sensing range.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Cordyceps Stroma",
  "type": "action",
  "category": "anti-ant",
  "displayCategory": "engine",
  "buyCostEnergy": 18,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "ant",
  "produces": "",
  "effect": "Once per 10 rounds: destroy the nearest ant nest within sensing range.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 }
];

export const CARD_BY_NAME = Object.fromEntries(CARD_DATA.map((c) => [c.name, c]));
