// =============================================================================
// Card data — GENERATED from docs/cards.json (do not edit by hand).
// Regenerate: node scripts/gen-carddata.mjs
// Engine-relevant fields only. Effects are dispatched by name in engine/cards.js.
// =============================================================================
export const CARD_DATA = [
 {
  "name": "Hyphal Extension",
  "type": "basic",
  "category": "growth",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 1 step: toward all food sources in range.",
  "family": "basics",
  "tutorial": true,
  "startCopies": 5
 },
 {
  "name": "Leaf Litter Cache",
  "type": "basic",
  "category": "substrate",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a SMALL nutrient patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Acorn Cache",
  "type": "basic",
  "category": "substrate",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a SMALL nut cache at the edge of sensing range.",
  "family": "basics",
  "tutorial": true,
  "startCopies": 5
 },
 {
  "name": "Apical Drive",
  "type": "basic",
  "category": "growth",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 2 steps: choose a direction.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Foraging Fan",
  "type": "basic",
  "category": "growth",
  "buyCostEnergy": 0,
  "costW": 2,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 1 step: every direction.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Tropic Lunge",
  "type": "basic",
  "category": "growth",
  "buyCostEnergy": 0,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow 5 steps toward the nearest food source, even if out of range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Humus Bed",
  "type": "basic",
  "category": "substrate",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "early",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a MEDIUM patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Mycorrhizal Mat",
  "type": "basic",
  "category": "substrate",
  "buyCostEnergy": 0,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Pick a direction; drop a LARGE patch at the edge of sensing range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Saprotrophic Digest",
  "type": "basic",
  "category": "economy",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Drain 1 nutrient from every occupied food source, doubling the energy received.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Appressorial Punch",
  "type": "basic",
  "category": "utility",
  "buyCostEnergy": 0,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Grow hyphae through one selected rock in-range.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Sclerotial Crust",
  "type": "basic",
  "category": "defense",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "all",
  "produces": "",
  "effect": "Tap a point: strands within radius 40 harden — immune to infection and eating for 2 rounds.",
  "family": "basics",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Hyphal Imbibition",
  "type": "basic",
  "category": "water-harvest",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+9 Water lakeside / +3 Water from soil",
  "effect": "If your network touches a lake edge, harvest +9 Water. Otherwise gain +3 Water from soil.",
  "family": "water",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Phosphate Tap",
  "type": "basic",
  "category": "phosphorus-mining",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+3 Phosphorus on harvest",
  "effect": "If your network contacts any mineral, crystal, or boulder, harvest +3 Phosphorus.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Condense",
  "type": "basic",
  "category": "water-harvest",
  "buyCostEnergy": 0,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "+3 Water",
  "effect": "Gain 3 Water.",
  "family": "water",
  "tutorial": false,
  "startCopies": 5
 },
 {
  "name": "Rhizomorph Trunkline",
  "type": "engine",
  "category": "energy income",
  "buyCostEnergy": 22,
  "costW": 0,
  "costP": 0,
  "timing": "mid",
  "repay": 3,
  "threat": "none",
  "produces": "+4 energy/round",
  "effect": "Install. Gain +4 energy at the end of each round.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Osmotic Cashout",
  "type": "event",
  "category": "energy burst",
  "buyCostEnergy": 12,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Exhaust (1 Water): gain +22 energy.",
  "family": "energy",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Septal Pore Flux",
  "type": "engine",
  "category": "cheaper draws",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 3,
  "threat": "none",
  "produces": "-3 energy per draw (savings)",
  "effect": "Install. Drawing cards costs 3 less energy.",
  "family": "energy",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Aquaporin Channels",
  "type": "engine",
  "category": "water-engine",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 4,
  "threat": "none",
  "produces": "+1 Water / 2 rounds",
  "effect": "Install. Gain +1 Water every 2 rounds.",
  "family": "water",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Phosphatase Cushion",
  "type": "engine",
  "category": "phosphorus-producer",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 3,
  "threat": "none",
  "produces": "+1 Phosphorus / round (lifetime cap 8)",
  "effect": "Install. Gain +1 Phosphorus at the end of each round.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Mineralizing Saprobe",
  "type": "engine",
  "category": "decay / unconditional P production",
  "buyCostEnergy": 14,
  "costW": 0,
  "costP": 0,
  "timing": "early",
  "repay": 4,
  "threat": "none",
  "produces": "1 P / round (unconditional)",
  "effect": "Install. Gain +1 Phosphorus at the end of each round.",
  "family": "phosphorus",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Tap-Root Rhizomorph",
  "type": "action",
  "category": "routing",
  "buyCostEnergy": 12,
  "costW": 0,
  "costP": 2,
  "timing": "mid",
  "repay": 4,
  "threat": "none",
  "produces": "+1 cleared formation/column per round it has a target (~5 energy-equiv of barrier bypass)",
  "effect": "Once per 5 rounds: Pay 2 P to grow through an in-range rock.",
  "family": "growth",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Constricting Ring",
  "type": "action",
  "category": "anti-worm",
  "buyCostEnergy": 5,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "worm",
  "produces": "",
  "effect": "Once per 6 rounds: tap a point where no nematode is within range; the first to enter is digested for +2 P.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Rehydration Pulse",
  "type": "event",
  "category": "water-repair",
  "buyCostEnergy": 7,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "all",
  "produces": "",
  "effect": "Exhaust (1 Water): tap a point; heal all worm/mould damage within radius 60.",
  "family": "water",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Nutrient Transmutation",
  "type": "action",
  "category": "resource converter",
  "buyCostEnergy": 6,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Action (once per round): spend 2 of one resource (W/P) to gain 1 of the other.",
  "family": "phosphorus",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Rhizomorph Lance",
  "type": "event",
  "category": "mobility",
  "buyCostEnergy": 10,
  "costW": 2,
  "costP": 0,
  "timing": "mid",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Exhaust (2 Water): pick a direction; instantly grow up to 6 steps that way.",
  "family": "events",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Fruiting Vigil",
  "type": "event",
  "category": "finisher",
  "buyCostEnergy": 12,
  "costW": 2,
  "costP": 2,
  "timing": "late",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Exhaust (2 Water + 2 Phosphorus): pick the goal direction and extend up to 6 steps.",
  "family": "events",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Leading Cord",
  "type": "action",
  "category": "growth",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to grow 2 steps in a chosen direction.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Forager Bloom",
  "type": "action",
  "category": "growth",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to fan out and grow 1 step in every direction.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Questing Front",
  "type": "action",
  "category": "growth",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to grow toward the nearest food, even out of range.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Humus Cache",
  "type": "extender",
  "category": "draw-engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Humus Bed basics",
  "effect": "Shuffle 5 copies of Humus Bed into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Symbiont Weave",
  "type": "extender",
  "category": "draw-engine",
  "buyCostEnergy": 9,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Mycorrhizal Mat basics",
  "effect": "Shuffle 5 copies of Mycorrhizal Mat into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Enzyme Priming",
  "type": "extender",
  "category": "draw-engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Saprotrophic Digest basics",
  "effect": "Shuffle 5 copies of Saprotrophic Digest into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Boring Corps",
  "type": "action",
  "category": "routing",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 2,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 2 P to bore through an in-range rock.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Crust Reserve",
  "type": "action",
  "category": "anti-mould",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 P to harden a patch and clear mould there.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Capillary Runners",
  "type": "engine",
  "category": "water-engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Gain +3 Water every 6 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Prospecting Cords",
  "type": "engine",
  "category": "phosphorus-producer",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Gain +3 Phosphorus every 6 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Dew Traps",
  "type": "engine",
  "category": "water-engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Gain +3 Water every 6 rounds.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Colonizing Front",
  "type": "action",
  "category": "growth",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to grow 1 step toward all food in range.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Leaf Fall",
  "type": "extender",
  "category": "draw-engine",
  "buyCostEnergy": 8,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "Leaf Litter Cache basics",
  "effect": "Shuffle 5 copies of Leaf Litter Cache into your draw deck.",
  "family": "extenders",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Acorn Fall",
  "type": "action",
  "category": "substrate",
  "buyCostEnergy": 8,
  "costW": 1,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Once per 6 rounds: pay 1 W to bury a small nut cache at the sensing edge.",
  "family": "installs",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Sclerotial Seal",
  "type": "action",
  "category": "anti-ant",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "ant",
  "produces": "",
  "effect": "Once per 4 rounds: Pay 1 P to seal any food pile from ant access.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Suberin Wall",
  "type": "action",
  "category": "anti-mould",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 1,
  "timing": "any",
  "repay": 0,
  "threat": "mould",
  "produces": "",
  "effect": "Once per 3 rounds: tap a point to clear all infection and protect from reinfection for 2 rounds.",
  "family": "defense",
  "tutorial": false,
  "startCopies": 0
 },
 {
  "name": "Quickened Reflex",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every installed action is ready 1 round sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Impulse Relay",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 18,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every installed action is ready 2 rounds sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Hair-Trigger Hyphae",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 28,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every installed action is ready 3 rounds sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Brisk Metabolism",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 10,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every resource engine pays out 1 round sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Enzyme Overclock",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 18,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every resource engine pays out 2 rounds sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 },
 {
  "name": "Metabolic Surge",
  "type": "engine",
  "category": "tempo",
  "buyCostEnergy": 28,
  "costW": 0,
  "costP": 0,
  "timing": "any",
  "repay": 0,
  "threat": "none",
  "produces": "",
  "effect": "Install. Every resource engine pays out 3 rounds sooner.",
  "family": "tempo",
  "tutorial": true,
  "startCopies": 0
 }
];

export const CARD_BY_NAME = Object.fromEntries(CARD_DATA.map((c) => [c.name, c]));
