// GENERATED by scripts/gen-levels.mjs from docs/levels/*.json — DO NOT EDIT.
//
// Hand-authored levels (docs/level-editor.html). A level whose `campaignLevel` is
// set REPLACES the procedural map for that campaign level; others are inert here.
// To add one: export the JSON from the editor into docs/levels/, run
// `node scripts/gen-levels.mjs`, then `node build.mjs`.

export const LEVELS = [
  
];

// The authored level for campaign level `n`, or null to generate procedurally.
export function levelForNumber(n) {
  for (const l of LEVELS) if ((l.campaignLevel | 0) === (n | 0) && l.campaignLevel != null) return l;
  return null;
}
